apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubernetes.io/created-by: kubesphere.io/ks-router
  name: system:nginx-ingress-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kubesphere-router-clusterrole
subjects:
- kind: ServiceAccount
  name: kubesphere-router-serviceaccount
  namespace: sample-namespace
