apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubernetes.io/created-by: kubesphere.io/ks-router
  name: nginx-ingress-role-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:kubesphere-router-role
subjects:
- kind: ServiceAccount
  name: kubesphere-router-serviceaccount

