/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "kubesphere.io/kubesphere/pkg/apis/types/v1beta1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// FederatedWorkspacesGetter has a method to return a FederatedWorkspaceInterface.
// A group's client should implement this interface.
type FederatedWorkspacesGetter interface {
	FederatedWorkspaces() FederatedWorkspaceInterface
}

// FederatedWorkspaceInterface has methods to work with FederatedWorkspace resources.
type FederatedWorkspaceInterface interface {
	Create(ctx context.Context, federatedWorkspace *v1beta1.FederatedWorkspace, opts v1.CreateOptions) (*v1beta1.FederatedWorkspace, error)
	Update(ctx context.Context, federatedWorkspace *v1beta1.FederatedWorkspace, opts v1.UpdateOptions) (*v1beta1.FederatedWorkspace, error)
	UpdateStatus(ctx context.Context, federatedWorkspace *v1beta1.FederatedWorkspace, opts v1.UpdateOptions) (*v1beta1.FederatedWorkspace, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.FederatedWorkspace, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.FederatedWorkspaceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FederatedWorkspace, err error)
	FederatedWorkspaceExpansion
}

// federatedWorkspaces implements FederatedWorkspaceInterface
type federatedWorkspaces struct {
	client rest.Interface
}

// newFederatedWorkspaces returns a FederatedWorkspaces
func newFederatedWorkspaces(c *TypesV1beta1Client) *federatedWorkspaces {
	return &federatedWorkspaces{
		client: c.RESTClient(),
	}
}

// Get takes name of the federatedWorkspace, and returns the corresponding federatedWorkspace object, and an error if there is any.
func (c *federatedWorkspaces) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.FederatedWorkspace, err error) {
	result = &v1beta1.FederatedWorkspace{}
	err = c.client.Get().
		Resource("federatedworkspaces").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FederatedWorkspaces that match those selectors.
func (c *federatedWorkspaces) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.FederatedWorkspaceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.FederatedWorkspaceList{}
	err = c.client.Get().
		Resource("federatedworkspaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested federatedWorkspaces.
func (c *federatedWorkspaces) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("federatedworkspaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a federatedWorkspace and creates it.  Returns the server's representation of the federatedWorkspace, and an error, if there is any.
func (c *federatedWorkspaces) Create(ctx context.Context, federatedWorkspace *v1beta1.FederatedWorkspace, opts v1.CreateOptions) (result *v1beta1.FederatedWorkspace, err error) {
	result = &v1beta1.FederatedWorkspace{}
	err = c.client.Post().
		Resource("federatedworkspaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedWorkspace).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a federatedWorkspace and updates it. Returns the server's representation of the federatedWorkspace, and an error, if there is any.
func (c *federatedWorkspaces) Update(ctx context.Context, federatedWorkspace *v1beta1.FederatedWorkspace, opts v1.UpdateOptions) (result *v1beta1.FederatedWorkspace, err error) {
	result = &v1beta1.FederatedWorkspace{}
	err = c.client.Put().
		Resource("federatedworkspaces").
		Name(federatedWorkspace.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedWorkspace).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *federatedWorkspaces) UpdateStatus(ctx context.Context, federatedWorkspace *v1beta1.FederatedWorkspace, opts v1.UpdateOptions) (result *v1beta1.FederatedWorkspace, err error) {
	result = &v1beta1.FederatedWorkspace{}
	err = c.client.Put().
		Resource("federatedworkspaces").
		Name(federatedWorkspace.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedWorkspace).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the federatedWorkspace and deletes it. Returns an error if one occurs.
func (c *federatedWorkspaces) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("federatedworkspaces").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *federatedWorkspaces) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("federatedworkspaces").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched federatedWorkspace.
func (c *federatedWorkspaces) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FederatedWorkspace, err error) {
	result = &v1beta1.FederatedWorkspace{}
	err = c.client.Patch(pt).
		Resource("federatedworkspaces").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
