/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "kubesphere.io/kubesphere/pkg/apis/types/v1beta1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// FederatedUsersGetter has a method to return a FederatedUserInterface.
// A group's client should implement this interface.
type FederatedUsersGetter interface {
	FederatedUsers(namespace string) FederatedUserInterface
}

// FederatedUserInterface has methods to work with FederatedUser resources.
type FederatedUserInterface interface {
	Create(ctx context.Context, federatedUser *v1beta1.FederatedUser, opts v1.CreateOptions) (*v1beta1.FederatedUser, error)
	Update(ctx context.Context, federatedUser *v1beta1.FederatedUser, opts v1.UpdateOptions) (*v1beta1.FederatedUser, error)
	UpdateStatus(ctx context.Context, federatedUser *v1beta1.FederatedUser, opts v1.UpdateOptions) (*v1beta1.FederatedUser, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.FederatedUser, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.FederatedUserList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FederatedUser, err error)
	FederatedUserExpansion
}

// federatedUsers implements FederatedUserInterface
type federatedUsers struct {
	client rest.Interface
	ns     string
}

// newFederatedUsers returns a FederatedUsers
func newFederatedUsers(c *TypesV1beta1Client, namespace string) *federatedUsers {
	return &federatedUsers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the federatedUser, and returns the corresponding federatedUser object, and an error if there is any.
func (c *federatedUsers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.FederatedUser, err error) {
	result = &v1beta1.FederatedUser{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("federatedusers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FederatedUsers that match those selectors.
func (c *federatedUsers) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.FederatedUserList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.FederatedUserList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("federatedusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested federatedUsers.
func (c *federatedUsers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("federatedusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a federatedUser and creates it.  Returns the server's representation of the federatedUser, and an error, if there is any.
func (c *federatedUsers) Create(ctx context.Context, federatedUser *v1beta1.FederatedUser, opts v1.CreateOptions) (result *v1beta1.FederatedUser, err error) {
	result = &v1beta1.FederatedUser{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("federatedusers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedUser).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a federatedUser and updates it. Returns the server's representation of the federatedUser, and an error, if there is any.
func (c *federatedUsers) Update(ctx context.Context, federatedUser *v1beta1.FederatedUser, opts v1.UpdateOptions) (result *v1beta1.FederatedUser, err error) {
	result = &v1beta1.FederatedUser{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("federatedusers").
		Name(federatedUser.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedUser).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *federatedUsers) UpdateStatus(ctx context.Context, federatedUser *v1beta1.FederatedUser, opts v1.UpdateOptions) (result *v1beta1.FederatedUser, err error) {
	result = &v1beta1.FederatedUser{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("federatedusers").
		Name(federatedUser.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(federatedUser).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the federatedUser and deletes it. Returns an error if one occurs.
func (c *federatedUsers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("federatedusers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *federatedUsers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("federatedusers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched federatedUser.
func (c *federatedUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FederatedUser, err error) {
	result = &v1beta1.FederatedUser{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("federatedusers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
