name: Go

on:
  push:
    branches:
      - 'CICD'
      - 'release*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'CICD'
      - 'release*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Check pr is properly formatted
        run: diff -u <(echo -n) <(gofmt -d ./pkg ./cmd ./tools ./test)

      - name: Downloading go dependencies
        run: go mod vendor

      - name: Build
        run: |
          make ks-apiserver
          make controller-manager

      - name: Get branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build and push docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name == 'push'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          bash hack/docker_build.sh ${{ steps.extract_branch.outputs.branch }}

      - name: executing remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 31232
          script: |
            kubectl -n kubesphere-system set image deployment/ks-apiserver ks-apiserver=zackzhangkai/ks-apiserver --record
            kubectl -n kubesphere-system set image deployment/ks-controller-manager ks-controller-manager=zackzhangkai/ks-controller-manager --record
            kubectl -n kubesphere-system rollout restart deploy/ks-apiserver
            kubectl -n kubesphere-system rollout restart deploy/ks-controller-manager
